import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:posthog_flutter/posthog_flutter.dart';
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'core/config/env.dart';
import 'firebase_options.dart';
import 'app.dart';
import 'core/services/analytics_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Env.assertConfigured();

  // Firebase — required for Firebase Messaging token registration and push opens.
  // `firebase_options.dart` is generated by `flutterfire configure`.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Supabase — must be initialized before any widget uses `Supabase.instance`.
  // authFlowType: pkce is required for OAuth deep-link callbacks on iOS/Android.
  await Supabase.initialize(
    url: Env.supabaseUrl,
    anonKey: Env.supabaseAnonKey,
    authOptions: const FlutterAuthClientOptions(
      authFlowType: AuthFlowType.pkce,
    ),
  );

  // Midtrans — initialized lazily by `MidtransService` the first time the
  // paywall opens (see `lib/core/services/midtrans_service.dart`). Keeping it
  // out of the startup path means free-tier users never pay the SDK's init
  // cost, and we avoid touching platform channels before the first frame.

  // PostHog — native init is configured in Info.plist / AndroidManifest.xml.
  // With native-only init, no Dart setup() call is needed; the SDK auto-
  // initializes on first use. Identification happens on login
  // (see Analytics.identify in core/services/analytics_service.dart).

  // Sentry — wraps runApp to capture uncaught zone errors.
  await SentryFlutter.init((options) {
    options.dsn = Env.sentryDsn;
    options.tracesSampleRate = 0.2; // 20% of transactions
    options.profilesSampleRate = 0.2;
    options.environment = Env.sentryEnv;
  }, appRunner: () => runApp(const ProviderScope(child: LoitApp())));

  // Temporary smoke test: fire one event and flush immediately so it reaches
  // the dashboard without waiting for the 30 s batch. Remove once verified.
  await Analytics.signUp('email');
  await Posthog().flush();
}
